version: "3.7"
services:
  webapp:
    container_name: modimio
    build:
      context: docker
      dockerfile: ./Dockerfile
    ports:
      - "9910:80"
    volumes:
      - ./:/var/www/public
    environment:
      - APP_ENV=development
